server:
  port: 8088
  servlet:
    context-path: /api/v1


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasksDB
    username: postgres
    password: 32167
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect