server:
  port: 8088
  servlet:
    context-path: /api/v1


spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/tasksDB
    username: postgres
    password: 32167
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  artemis:
    user: 'artemis'
    password: 'simetraehcapa'
  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: 'taskeditor.service'
    password: 'axdeolneadrkgymh'
    properties:
      mail:
        smtp:
          auth: 'true'
          starttls:
            enable: 'true'


jwt:
  secret: M3cyb2k0dXJoZjM5NGdoZjM0OTdnOTQ4dHlyaDA0MjgzaGk4d3JlZ2Y4M3c0Z2Y4NzM0eXRvMzRodDk4aDgmRyomXkY3ZjNyODdnaWhkc2Y=
  lifetime: 36000000


logging:
  level:
    root: INFO
    ru.krisnovitskaya.TasksMultiEditor: DEBUG